PROC FORMAT;
VALUE $ VTIPO a='Placebo'
			b='Estándar'
			c='Nuevo';
RUN;

DATA SOMNIFERO;
INFILE '/folders/myfolders/DAT02/DATATAB_6_33.csv' DLM=',' FIRSTOBS=2;
INPUT TIPO $ HSUENYO;
FORMAT TIPO VTIPO.;
RUN;
PROC PRINT;RUN;

PROC BOXPLOT DATA=SOMNIFERO;
PLOT HSUENYO*TIPO;
RUN;

PROC ANOVA DATA=SOMNIFERO;
CLASS TIPO;
MODEL HSUENYO=TIPO;
MEANS TIPO/DUNNETT('Placebo');
RUN;

PROC GLM;
CLASS TIPO;
MODEL HSUENYO=TIPO/CLPARM;
CONTRAST 'Eficacia de somnifero nuevo' TIPO -1 1 0/E;
ESTIMATE 'Eficacia de somnifero nuevo' TIPO -1 1 0;
RUN;